### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Rmlawo** [seiuna/pukoudai-client#5]
这个怎么解决啊
![IMG_20231122_182553](https://github.com/seiuna/pukoudai-client/assets/151734214/fa6b634b-0ae4-4a8c-96c0-f38e173f48c7)

**Comment by seiuna** [comment]
https://github.com/seiuna/pukoudai-client/tree/8b5dc7fa0d592cd6a8d507055f12a2dfdae1907d

**Comment by Rmlawo** [comment]
Ok解决了
