### ISSUE TITLE
新版抢到活动的速度远没有以前的高了

### ISSUE THREAD

**Issue by nxygen** [seiuna/pukoudai-client#6]
新的推送相较于十一月二十号左右的推送来说，成功抢到活动的概率低了很多，原本在ubuntu22.04环境下，npm20，几乎是100ms左右触发报名，新版脚本则会出现更多的cd中，过了两三秒这样（甚至更长时间）才能报名成功。
另外，我想问一下，这个登录设备判定是什么，假如我在一台机器上使用hyperv来虚拟两台机器来抢活动，会出现cd频繁嘛，我试过挂载两个脚本在一台机器上，会卡频繁

**Comment by seiuna** [comment]
会 因为活动报名有一个两秒的cd。多个活动和客户端都共享这个cd。 也就是说你不能在同一时间报名多个活动，以及在多个客户端在同一时间报名一个或者活动。所以我为client 的 joinevent 函数 加了一个内置的cd 如果在cd内 则会直接返回操作频繁。

**Comment by nxygen** [comment]
好的感谢解答，还是希望作者能将程序调整到一个合适的状态，保证活动抢到，本人水平较差，无能力编写

**Comment by seiuna** [comment]
https://github.com/seiuna/puu-uuuuuuuuuuuu 用新的
